// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#ifndef _DASHBOARD_UI_UI_H
#define _DASHBOARD_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RightArrow;
extern lv_obj_t * ui_LeftArrow;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_ExampleWhite;
extern lv_obj_t * ui_ExampleYellow;
extern lv_obj_t * ui_ExampleRed;
extern lv_obj_t * ui_PowerLevel;
extern lv_obj_t * ui_BatLevel;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image5;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_NotConnected;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1346116439);    // assets/left-turn-signal.png
LV_IMG_DECLARE(ui_img_bolt_20dp_fill1_wght400_grad0_opsz20_png);    // assets/bolt_20dp_FILL1_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_battery_full_20dp_fill1_wght400_grad0_opsz20_png);    // assets/battery_full_20dp_FILL1_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(ui_img_official_logo_square_1_png);    // assets/Official_Logo_Square_1.png



LV_FONT_DECLARE(ui_font_BarlowBold120);
LV_FONT_DECLARE(ui_font_BarlowBold32);
LV_FONT_DECLARE(ui_font_BarlowMedium20);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
