// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NotConnected = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_NotConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NotConnected, 0);
    lv_obj_set_y(ui_NotConnected, -35);
    lv_obj_set_align(ui_NotConnected, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_NotConnected, "Not Connected");
    lv_obj_set_style_text_color(ui_NotConnected, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NotConnected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NotConnected, &ui_font_BarlowBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image6, &ui_img_official_logo_square_1_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 783
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 783
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -15);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 100);

}
